name: bad pipeline

# Указывем, когда запускать pipeline
on:
  pull_request:
    branches: [ "main" ]

# Указываем уровень доступа в репозитории
permissions:
  contents: read

# Указываем задачи, которые будут выполняться при выполнении pipeline
jobs:

  # Задача build
  build:

    # Образ, на котором будет выполняться задача
    runs-on: ubuntu-latest

    # Шаги выполнения задачи
    steps:

      # Шаг проверок от actions
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг установки JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      # Шаг установки Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1

      # Шаг сборки проекта через ./gradlew
      - name: Run build with Gradle Wrapper
        run:
          ./gradlew clean build

      # Шаг авторизации в сервисе Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг сборки образа
      - name: Build image
        run: |
          docker build -t animal-tracking .

      # Шаг создания нового тега образа
      - name: Tag image
        run: |
          docker tag animal-tracking bengobro/lab-4

      # Шаг отправки образа в Docker Hub
      - name: Build and push
        run: |
          docker push bengobro/lab-4
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to remote server
        run: |
          sshpass -p ${{ secrets.SSH_PRIVATE_KEY }} ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }}
        env:
          SSHPASS: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: Pull image
        run: |
          docker pull ${{ vars.DOCKERHUB_REPOSITORY }}:${{ vars.DOCKER_TAG_VERSION }}

      - name: Run container
        run: |
          docker run ${{ vars.DOCKERHUB_REPOSITORY }}:${{ vars.DOCKER_TAG_VERSION }}

      - name: Stop container
        run: |
          docker stop ${{ vars.DOCKERHUB_REPOSITORY }}:${{ vars.DOCKER_TAG_VERSION }}