name: Good Pipeline

# Указывем, когда запускать pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Указываем уровень доступа в репозитории
permissions:
  contents: read

# Указываем задачи, которые будут выполняться при выполнении pipeline
jobs:

  # Прогонка тестов проекта
  Test:

    # Образ, на котором будет выполняться задача
    runs-on: ubuntu-latest

    # Шаги выполнения задачи
    steps:

      # Шаг проверок от actions
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг установки JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      # Шаг установки Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1

      # Шаг сборки проекта через ./gradlew
      - name: Run tests
        run:
          ./gradlew clean build

  # Сборка и отправка в Docker Hub образа Docker
  Publish:

    # Образ, на котором будет выполняться задача
    runs-on: ubuntu-latest

    # Шаги выполнения задачи
    steps:

      # Шаг проверок от actions
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг установки JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      # Шаг установки Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1

      # Шаг сборки проекта через ./gradlew
      - name: Run build
        run:
          ./gradlew clean build -x test

      # Шаг авторизации в сервисе Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг сборки образа
      - name: Build image
        run: |
          docker build -t animal-tracking .

      # Шаг создания нового тега образа
      - name: Tag image
        run: |
          docker tag animal-tracking bengobro/lab-4

      # Шаг отправки образа в Docker Hub
      - name: Build and push
        run: |
          docker push bengobro/lab-4