name: ci

# Указывем, когда запускать pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Указываем уровень доступа в репозитории
permissions:
  contents: read

# Указываем задачи, которые будут выполняться при выполнении pipeline
jobs:

  # Задача build
  build:

    # Образ, на котором будет выполняться задача
    runs-on: ubuntu-latest

    # Шаги выполнения задачи
    steps:

      # Шаг проверок от actions. Внутри происходят проверки версии git, репозитория; копирование репозитория в контейнер
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг установки JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      # Шаг установки Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1

      # Шаг сборки проекта через ./gradlew
      - name: Run build with Gradle Wrapper
        run:
          ./gradlew clean build

      - name: Echo /build/libs
        run: ls build/libs

      # Шаг авторизации в сервисе Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag image
        run: |
          docker build -t animal-tracking:latest .

#      # Шаг настройки Docker-образа
#      - name: Set up Docker image
#        uses: docker/setup-buildx-action@v3
#
      # Шаг сборки Docker-образа и его отправки в Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/clockbox:latest